version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/python"
    schedule: { interval: "weekly" }
  - package-ecosystem: "nuget"
    directory: "/dotnet"
    schedule: { interval: "weekly" }
