repos:
  # (optional) keep your Python tidy
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        language_version: python3

  # Jupytext hook: keeps sieve.py <-> sieve.ipynb in lockstep
  - repo: https://github.com/pre-commit/mirrors-jupytext
    rev: v1.16.3
    hooks:
      - id: jupytext
        name: jupytext (sync sieve.py <-> sieve.ipynb)
        files: ^sieve\.(ipynb|py)$
        args:
          - --set-formats=ipynb,py:percent
          - --sync
