repos:
  # (optional) keep your Python tidy
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        language_version: python3

  # Jupytext hook: keeps sieve.py <-> sieve.ipynb in lockstep
  - repo: https://github.com/pre-commit/mirrors-jupytext
    rev: v1.16.3
    hooks:
      - id: jupytext
        name: jupytext (sync sieve.py <-> sieve.ipynb)
        files: ^sieve\.(ipynb|py)$
        args:
          - --set-formats=ipynb,py:percent
          - --sync

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: validate-capsules
        name: validate capsules
        entry: python python/validate_capsules.py
        language: system
        files: ^capsules/.*\.json$
        exclude: ^capsules/_.*\.json$
        pass_filenames: false
