name: Bug
description: Something broke
body:
  - type: textarea
    id: repro
    attributes:
      label: Repro steps
      description: exact commands, inputs, commits
    validations: { required: true }
  - type: textarea
    id: expected
    attributes:
      label: Expected vs actual
    validations: { required: true }
