import Brain.Proof.Prelude
import Brain.Proof.GridCert

-- main executable target compiles the autogenerated GridCert and its theorem
def main : IO Unit := do
  IO.println s!"K-witness theorem compiled. THRESH={Brain.Proof.THRESH} OK."
