name = "brain"
version = "0.1.0"
timeout = 60000

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.23.0-rc2"  # <-- pin to what CI used; update later via PR bot
