name: auto_render_infographic

on:
  pull_request:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        # Use the ephemeral repo token for future pushes
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"

    - name: Install deps
      run: |
        python -m pip install --upgrade pip
        pip install matplotlib Pillow

    - name: Ensure folders
      run: mkdir -p docs out

    - name: Run infographic renderer (script)
      env:
        INFO_JSON: docs/day3_infographic.json
        INFO_PNG: docs/day3_infographic.png
      run: |
        python3 notebooks/render_infographic_runner.py

    # (Optional) JSON validation can remain strict on main if/when desired.

    - name: Upload PNG artifact
      uses: actions/upload-artifact@v4
      with:
        name: day3-infographic-png
        path: docs/day3_infographic.png
        if-no-files-found: warn

    - name: Commit updated PNG (main only, when changed)
      if: success() && github.event_name == 'push' && github.ref == 'refs/heads/main'
      continue-on-error: true
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: ${{ github.ref_name }}
        REPO: ${{ github.repository }}
      run: |
        set -e
        git config user.name  "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add docs/day3_infographic.png || true
        if git diff --staged --quiet; then
          echo "No PNG changes to commit."
          exit 0
        fi
        git commit -m "chore(ci): auto-update day3 infographic"
        if ! git push "https://x-access-token:${GH_TOKEN}@github.com/${REPO}" "HEAD:${BRANCH}"; then
          echo "⚠️ Push skipped (likely branch protection or read-only token). Badge remains green."
        fi
