name: CI - Infographic / render

on:
  push:
    branches: [ "main" ]
  pull_request:
    paths:
      - "notebooks/render_infographic.ipynb"
      - "docs/day3_infographic.json"
      - "schema/infographic.schema.json"
      - ".github/workflows/auto_render_infographic.yml"
  workflow_dispatch:

jobs:
  render:
    runs-on: ubuntu-latest
    env:
      # PRs run in "SMOKE" mode (skip hard validation, allow notebook to render)
      SMOKE: ${{ github.event_name == 'pull_request' && '1' || '0' }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install nbconvert nbclient jupyter jsonschema matplotlib pillow

      - name: Validate infographic JSON against schema (skipped in SMOKE)
        if: env.SMOKE != '1'
        run: |
          if [ ! -f schema/infographic.schema.json ] || [ ! -f docs/day3_infographic.json ]; then
            echo "Schema or JSON missing, skipping validation."
            exit 0
          fi
          python - <<'PY'
import json, jsonschema, sys
schema = json.load(open('schema/infographic.schema.json'))
data   = json.load(open('docs/day3_infographic.json'))
jsonschema.validate(data, schema)
print("✅ JSON schema validation passed")
PY

      - name: Execute notebook (headless)
        run: |
          # allow_errors keeps the PNG step alive in smoke situations
          python -m nbconvert --to notebook --execute \
            --ExecutePreprocessor.allow_errors=True \
            notebooks/render_infographic.ipynb \
            --output /tmp/render_output.ipynb

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: day3-infographic
          path: |
            docs/day3_infographic.png
            docs/day3_infographic.json
