name: Auto-render infographic

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

# Needed only if you keep the "commit back" step enabled.
permissions:
  contents: write

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install jupyter nbconvert matplotlib pillow jsonschema

      - name: Execute infographic notebook
        run: |
          python -m nbconvert --to notebook --execute \
            notebooks/render_infographic.ipynb \
            --output /tmp/render_infographic_out.ipynb
        # Notebook should write docs/day3_infographic.png

      - name: Validate metadata (if present)
        run: |
          if [ -f docs/day3_infographic.json ]; then
            python - <<'PY'
import json, jsonschema
schema = json.load(open('schema/infographic.schema.json'))
data = json.load(open('docs/day3_infographic.json'))
jsonschema.validate(data, schema)
print("OK: docs/day3_infographic.json matches schema")
PY
          else
            echo "No docs/day3_infographic.json found; skipping validation."
          fi

      - name: Upload PNG as artifact (safe)
        uses: actions/upload-artifact@v4
        with:
          name: day3-infographic
          path: docs/day3_infographic.png

      # OPTIONAL: commit the PNG back to the repo on main
      - name: Commit updated PNG to docs/ (optional)
        if: github.ref == 'refs/heads/main'
        run: |
          set -e
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/day3_infographic.png || true
          if ! git diff --staged --quiet; then
            git commit -m "Auto-render: update day3_infographic.png"
            git push origin HEAD:main
          else
            echo "No PNG changes to commit."
          fi
