name: Auto-render infographic

on:
  push:
    branches: [ "main" ]
    paths:
      - "notebooks/render_infographic.ipynb"
      - "capsules/**"
      - "schema/**"
      - ".github/workflows/auto_render_infographic.yml"
      - "tools/inject_smoke_cell.py"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  render:
    runs-on: ubuntu-latest
    env:
      SMOKE: "1"             # run the notebook in smoke mode on CI
      PYTHONUNBUFFERED: "1"
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install minimal toolchain
        run: |
          python -m pip install --upgrade pip
          # Pin versions for stable headless execution
          python -m pip install "nbconvert==7.*" "jupyter==1.*" pillow jsonschema matplotlib

      - name: Inject smoke guard cell (idempotent)
        run: |
          python tools/inject_smoke_cell.py notebooks/render_infographic.ipynb

      - name: Execute (smoke) notebook headlessly
        run: |
          python -m nbconvert --to notebook --execute \
            --ExecutePreprocessor.timeout=150 \
            --output /tmp/render_out.ipynb \
            notebooks/render_infographic.ipynb

      - name: Validate metadata against schema (if present)
        run: |
          if [ -f schema/infographic.schema.json ] && [ -f docs/day3_infographic.json ]; then
            python - <<'PY'
import json, jsonschema
jsonschema.validate(
  json.load(open('docs/day3_infographic.json')),
  json.load(open('schema/infographic.schema.json')),
)
print("JSON schema validation passed.")
PY
          else
            echo "Schema or JSON missing; skipping validation."
          fi

      - name: Upload PNG as artifact
        uses: actions/upload-artifact@v4
        with:
          name: day3-infographic-png
          path: docs/day3_infographic.png

      - name: Commit changed PNG back to repo (optional)
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/day3_infographic.png || true
          if ! git diff --staged --quiet; then
            git commit -m "Auto-render (smoke): update day3_infographic.png"
            git push
          else
            echo "No image changes to commit."
          fi
