name: CI - Bench

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

jobs:
  bench:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install numpy matplotlib pillow
      - name: Run bench (small)
        run: |
          set -e
          mkdir -p out gallery docs
          # locate bench.py in common locations
          BENCH=""
          for p in bench.py scripts/bench.py python/bench.py python/brain/bench.py; do
            if [ -f "$p" ]; then BENCH="$p"; break; fi
          done
          if [ -z "$BENCH" ]; then
            echo "❌ Could not find bench.py (checked root, scripts/, python/, python/brain/)."
            echo "Tip: place bench.py at repo root or set a stable path in ci-bench.yml."
            exit 1
          fi
          echo "➡ Running $BENCH ..."
          python "$BENCH" --traces 100000 --mode auto || true
      - name: Plot chart
        run: |
          python plot_bench.py bench_*.csv -o gallery/day4_bench.png || true
      - name: Build gallery HTML
        run: |
          python gallery.py --capsules "out/*.json" --out docs/gallery.html || true
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: day4-gallery
          path: |
            gallery/day4_bench.png
            docs/gallery.html
