name: CI - Capsules

on:
  push:
    branches: [main]

jobs:
  check-capsules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check for capsule files
        continue-on-error: true
        run: |
          if ls capsules/*.json >/dev/null 2>&1; then
            echo "✅ Capsules detected:"
            ls -1 capsules/*.json
          else
            echo "⚠️ No capsules found in /capsules (non-blocking)"
            exit 0
          fi
