name: CI - Capsules
on: [push, pull_request]

jobs:
  check-capsules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check for capsule files
        run: |
          if [ -z "$(ls capsules/*.json 2>/dev/null)" ]; then
            echo "❌ No capsules found in /capsules"
            exit 1
          else
            echo "✅ Capsules detected:"
            ls -1 capsules/*.json
          fi
