name: CI - Infographic
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install jsonschema nbformat nbconvert jupyter matplotlib
      - name: Validate infographic JSON against schema
        run: |
          python - <<'PY'
          import json, jsonschema
          schema = json.load(open('schema/infographic.schema.json'))
          data = json.load(open('docs/day3_infographic.json'))
          jsonschema.validate(instance=data, schema=schema)
          print('JSON schema validation \u2713')
          PY
      - name: Render PNG via notebook (headless)
        env:
          INFO_JSON: docs/day3_infographic.json
          INFO_PNG: docs/day3_infographic.png
        run: |
          jupyter nbconvert --to notebook --execute \
            --ExecutePreprocessor.timeout=240 \
            notebooks/render_infographic.ipynb \
            --output notebooks/render_infographic.out.ipynb
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: day3-infographic
          path: |
            docs/day3_infographic.png
            docs/day3_infographic.json
