name: proof-ci
on:
  push: { branches: ["**"] }
  pull_request: {}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with: { python-version: "3.11" }

      - name: Generate Lean GridCert
        run: |
          python scripts/gen_capsule_cert.py capsules/examples lean/Brain/Proof/GridCert.lean 90

      - name: Set up Lean
        uses: leanprover/lean-action@v1
        with:
          use-cache: true
          allow-sorry: true

      - name: Build (Lake)
        run: |
          lake update
          lake build
