name: CI - Proof v1.1 (smoke)
on: [push, pull_request]

jobs:
  proof-smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Python setup
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install pypdf

      - name: Run proof v1.1 smoke
        run: |
          python tools/proof_v1_1_smoke.py
