name: Lean 4 Proof Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lean:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Lean toolchain
        run: |
          curl -fsSL https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh | bash -s -- -y
          echo "$HOME/.elan/bin" >> $GITHUB_PATH
          TOOLCHAIN="$(cat lean/lean-toolchain)"
          ~/.elan/bin/elan toolchain install "$TOOLCHAIN"
          ~/.elan/bin/elan default "$TOOLCHAIN"
      - uses: leanprover/lean-action@v1
        with:
          project: brain/formal
          args: lake build PvsNP
