name: Lean 4 Proof Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lean:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: leanprover/lean-action@v1
        with:
          project: brain/formal
          args: lake build PvsNP
